import { BookOpen, ExternalLink, FlaskConical, GitPullRequest, Code2, UsersRound } from 'lucide-react';
import type { LiteratureSource, TestSmell } from '../types/testSmell';

export type CatalogPage = 'catalog' | 'methodology' | 'references' | 'contributors';

const REPOSITORY_URL = 'https://github.com/Intelvega/test-smells-catalog';

function PageTitle({ icon, eyebrow, title, children }: { icon: React.ReactNode; eyebrow: string; title: string; children: React.ReactNode }) {
  return <section className="rounded-xl border border-border bg-surface p-6 sm:p-8"><div className="mb-5 flex items-center gap-3 text-violet-300">{icon}<span className="text-xs font-medium uppercase tracking-[0.16em]">{eyebrow}</span></div><h2 className="text-2xl font-semibold text-ink sm:text-3xl">{title}</h2><div className="mt-4 max-w-3xl text-sm leading-relaxed text-ink-muted">{children}</div></section>;
}

function InfoCard({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-lg border border-border bg-surface p-5"><h3 className="text-base font-medium text-ink">{title}</h3><div className="mt-3 text-sm leading-relaxed text-ink-muted">{children}</div></section>;
}

export function MethodologyPage({ total }: { total: number }) {
  return <div className="space-y-5"><PageTitle icon={<FlaskConical size={20} />} eyebrow="Transparência" title="Metodologia do catálogo">O catálogo reúne <strong className="font-medium text-ink">{total} test smells</strong> para JavaScript e TypeScript. Cada cartão identifica a fonte que fundamenta sua descrição e oferece exemplos voltados ao ecossistema Jest/Vitest.</PageTitle><div className="grid gap-5 lg:grid-cols-2"><InfoCard title="Seleção e normalização"><p>Os smells foram reunidos a partir de Meneses, SNUTS.js, Steel, <em>The Open Catalog of Test Smells</em> e catálogos ReadTheDocs. Nomes equivalentes foram normalizados para reduzir duplicação; quando uma fonte usa outro nome, o cartão mantém o termo adotado e aponta a página equivalente.</p></InfoCard><InfoCard title="Definições e consequências"><p>As definições, consequências e estratégias de refatoração são sínteses em português das fontes listadas no próprio smell. Elas não são transcrições literais dos trabalhos originais.</p></InfoCard><InfoCard title="Exemplos em JavaScript"><p>Os exemplos foram criados ou adaptados para mostrar o padrão em JavaScript, com foco em Jest e Vitest. Eles são exemplos didáticos: não representam código copiado de projetos de terceiros nem resultados de uma ferramenta executada sobre um repositório real.</p></InfoCard><InfoCard title="Flakiness"><p>A marcação “direta” é reservada a smells que descrevem falha intermitente. “Possível flakiness” indica um mecanismo plausível, identificado por tempo, ordem de execução, estado compartilhado, ambiente externo ou aleatoriedade. Isso não significa que todo teste com o smell falhará.</p></InfoCard></div><InfoCard title="Revisão e validação"><ul className="list-disc space-y-2 pl-5"><li>Revisão manual da associação entre smell, fonte e página específica quando disponível.</li><li>Revisão da coerência entre definição, consequência, detecção e exemplo.</li><li>Validação técnica do site com <code className="rounded bg-canvas px-1.5 py-0.5 text-violet-200">npm run lint</code> e <code className="rounded bg-canvas px-1.5 py-0.5 text-violet-200">npm run build</code>.</li></ul></InfoCard></div>;
}

function sourceKey(source: LiteratureSource) { return `${source.authors}|${source.year}|${source.title}|${source.url ?? ''}`; }

export function ReferencesPage({ smells }: { smells: TestSmell[] }) {
  const sources = [...new Map(smells.flatMap((smell) => smell.sources ?? []).map((source) => [sourceKey(source), source])).values()];
  const grouped = [...sources.reduce((groups, source) => { const key = `${source.authors} (${source.year})`; const current = groups.get(key) ?? []; current.push(source); groups.set(key, current); return groups; }, new Map<string, LiteratureSource[]>())].sort(([a], [b]) => a.localeCompare(b));
  return <div className="space-y-5"><PageTitle icon={<BookOpen size={20} />} eyebrow="Bibliografia" title="Referências">As fontes abaixo fundamentam os smells do catálogo. Nos cartões, uma referência com link abre a página específica usada para aquele smell.</PageTitle><div className="space-y-4">{grouped.map(([group, items]) => <details key={group} className="group rounded-lg border border-border bg-surface" open={items.length <= 3}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 text-sm font-medium text-ink"><span>{group}</span><span className="rounded-full border border-border px-2 py-0.5 text-xs font-normal text-ink-muted">{items.length} {items.length === 1 ? 'referência' : 'referências'}</span></summary><ul className="space-y-3 border-t border-border-soft px-5 py-4 text-sm leading-relaxed text-ink-muted">{items.map((source) => <li key={sourceKey(source)}>{source.url ? <a href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-violet-300 underline underline-offset-2 hover:text-violet-200"><em>{source.title}</em><ExternalLink size={13} /></a> : <em>{source.title}</em>}.</li>)}</ul></details>)}</div></div>;
}

export function ContributorsPage() {
  return <div className="space-y-5"><PageTitle icon={<UsersRound size={20} />} eyebrow="Projeto aberto" title="Contribuidores e colaboração">O catálogo é mantido de forma aberta para tornar a literatura sobre test smells mais acessível a estudantes, pesquisadores e profissionais de teste.</PageTitle><div className="grid gap-5 lg:grid-cols-2"><InfoCard title="Manutenção inicial"><p><strong className="font-medium text-ink">Intelvega</strong> mantém o repositório, a curadoria do catálogo e a publicação do site.</p></InfoCard><InfoCard title="Reconhecimento das fontes"><p>As definições e classificações têm origem nas obras e catálogos listados em Referências. Cada smell aponta sua fonte para que leitores possam consultar a descrição original.</p></InfoCard></div><section className="rounded-lg border border-violet/30 bg-violet/10 p-5"><div className="flex items-start gap-3"><GitPullRequest className="mt-0.5 shrink-0 text-violet-300" size={19} /><div><h3 className="font-medium text-ink">Como contribuir</h3><p className="mt-2 text-sm leading-relaxed text-ink-muted">Sugira correções de referências, novos smells, exemplos melhores ou melhorias de interface pelo repositório. Pull requests e issues ajudam a manter o catálogo verificável.</p><a href={REPOSITORY_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-md border border-violet/40 px-3 py-2 text-sm font-medium text-violet-200 hover:bg-violet/10"><Code2 size={16} />Abrir repositório no GitHub<ExternalLink size={14} /></a></div></div></section></div>;
}

export function Footer({ onNavigate }: { onNavigate: (page: CatalogPage) => void }) { return <footer className="border-t border-border-soft py-6 text-center text-xs text-ink-faint"><p>Catálogo acadêmico de test smells em JavaScript e TypeScript.</p><div className="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-2"><button onClick={() => onNavigate('methodology')} className="hover:text-violet-300">Metodologia</button><button onClick={() => onNavigate('references')} className="hover:text-violet-300">Referências</button><button onClick={() => onNavigate('contributors')} className="hover:text-violet-300">Contribuidores</button><a href={REPOSITORY_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-violet-300"><Code2 size={13} />{'GitHub'}</a></div></footer>; }
